name: Cloud CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci

      - name: Fix Jest permissions
        run: chmod +x node_modules/.bin/jest

      - name: Verify Jest installation
        run: npx jest --version

      - name: Run tests
        run: npm test
